### ISSUE TITLE
Change peer dependancy to lower version of graphql

### ISSUE THREAD

**Issue by juliendesprez** [ivandotv/graphql-no-batched-queries#14]
https://github.com/ivandotv/graphql-no-batched-queries/blob/602bec13f008f31d63e2c80f06c74f0cdbca0f59/packages/no-batched-queries/package.json#L47

By implementing the lib on our project, we manager to use it and install with yarn hence we had graphql 15.5.1 installed and it was working fine (we made an artillery.io stress test to validate).

Problem is, our CI use NPM and our Dokerfile build is failing because NPM consider we do not match the peer dependancy of graphql. Ops don't want to force with options such as --legacy-peer-deps or --force

We cannot upgrade to 16.x.x because our Nest framework doesn't support it yet.

How to reproduce :
use graphql version < 16 in package.json
run npm install

**Comment by ivandotv** [comment]
Sorry. I won't downgrade graphql, even if it works with v15.
