### ISSUE TITLE
The readme is wrong

### ISSUE THREAD

**Issue by GauBen** [ivandotv/graphql-no-batched-queries#17]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/48261497/177195591-c932735a-b233-45e6-b856-6a0ccf38ffc4.png">

Hello, the readme of this package is from one of your other packages.

**Comment by ivandotv** [comment]
@GauBen 
Thanks for pointing this out, it's fixed.
https://www.npmjs.com/package/envelop-no-batched-queries
